### ISSUE TITLE
webchat wip

### ISSUE THREAD

**Issue by thomasrudin** [pandorabox-io/pandorabox.io#266]
* [x] https://github.com/pandorabox-io/beerchat (hooks, playername highlighting)
* [x] https://github.com/pandorabox-io/beerchat_web
* [x] setting `beerchat.url = http://beerchat-proxy:8080/api/message`
* [x] setting `secure.http_mods = beerchat_web`

docker-compose.yml
```
 beerchat-proxy:
  image: registry.rudin.io/x86/beerchat_proxy:latest
  environment:
   IRC_HOST: chat.freenode.net
   IRC_CHANNEL: pandorabox
   IRC_USERNAME: pandorabot
   IRC_PASSWORD: xxx
```
